### ISSUE TITLE
add functionality for start/stop button

### ISSUE THREAD

**Issue by Adimote** [sourcebots/robotd#4]
I think the way this should work with the API is the `import robot` call should block until the start button is pressed.

**Comment by kierdavis** [comment]
Don't forget to take into account pre-start code (e.g. setting servo positions so that the robot fits into the Cube of Judgement)

**Comment by kierdavis** [comment]
One way in which pre-start code could be handled is to provide two modules that could be implemented (e.g. `import robot.robot` vs `import robot.robot_nowait`), the only difference being that the former will wait for the start button after initialisation is completed whereas the latter won't.

**Comment by RealOrangeOne** [comment]
`pre-start` code is not supported yet, but the start button is
